Naxxramas_Loot = {
-- Abomination Wing --
	-- Patchwerk
    {["itemid"] = "22960", ["itemname"] = "Cloak of Suturing", ["classPriority"] = "Healers", ["note"] = ""},
    {["itemid"] = "22961", ["itemname"] = "Band of Reanimation", ["classPriority"] = "Hunter", ["note"] = ""},
    {["itemid"] = "22815", ["itemname"] = "Severance", ["classPriority"] = "Shaman (Enhance)", ["note"] = ""},
    {["itemid"] = "22820", ["itemname"] = "Wand of Fates", ["classPriority"] = "Warlock > Mage > Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "22818", ["itemname"] = "The Plague Bearer", ["classPriority"] = "Warrior", ["note"] = ""},
    -- Grobbulus
    {["itemid"] = "22967", ["itemname"] = "Icy Scale Spaulders", ["classPriority"] = "Hunter = Shaman (Enhance) > Warrior", ["note"] = ""},
    {["itemid"] = "22810", ["itemname"] = "Toxin Injector", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22988", ["itemname"] = "The End of Dreams", ["classPriority"] = "Priest (Shadow) = Druid (Resto) > Druid (Cat)", ["note"] = "*AQ Mace is 5 less AP, but 70+ Armour"},
    {["itemid"] = "22803", ["itemname"] = "Midnight Haze", ["classPriority"] = "Priest (Shadow) > Casters", ["note"] = ""},
    {["itemid"] = "22968", ["itemname"] = "Glacial Mantle", ["classPriority"] = "None", ["note"] = ""},
    -- Gluth
    {["itemid"] = "22994", ["itemname"] = "Digested Hand of Power", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22983", ["itemname"] = "Rime Covered Mantle", ["classPriority"] = "Mage > Priest (Shadow) = Warlock", ["note"] = ""},
    {["itemid"] = "22813", ["itemname"] = "Claymore of Unholy Might", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22981", ["itemname"] = "Gluth's Missing Collar", ["classPriority"] = "Warrior", ["note"] = ""},
    {["itemid"] = "23075", ["itemname"] = "Death's Bargain", ["classPriority"] = "None", ["note"] = ""},
    -- Thaddius
    {["itemid"] = "23070", ["itemname"] = "Leggings of Polarity", ["classPriority"] = "Mage = Warlock", ["note"] = ""},
    {["itemid"] = "22801", ["itemname"] = "Spire of Twilight", ["classPriority"] = "Priest (Holy) = Druid (Resto)", ["note"] = ""},
    {["itemid"] = "23001", ["itemname"] = "Eye of Diminution", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23000", ["itemname"] = "Plated Abomination Ribcage", ["classPriority"] = "Warrior (DPS)", ["note"] = ""},
    {["itemid"] = "22808", ["itemname"] = "The Castigator", ["classPriority"] = "Rogue* > Warrior (DPS) = Rogue", ["note"] = "*Rogue has Anubisath Warhammer"},

-- Deathknight Wing --
    -- Instructor Razuvious
    {["itemid"] = "23009", ["itemname"] = "Wand of the Whispering Dead", ["classPriority"] = "Priest (Holy)", ["note"] = ""},
    {["itemid"] = "23018", ["itemname"] = "Signet of the Fallen Defender", ["classPriority"] = "Tanks", ["note"] = ""},
    {["itemid"] = "23004", ["itemname"] = "Idol of Longevity", ["classPriority"] = "Druid (Resto)", ["note"] = ""},
    {["itemid"] = "23219", ["itemname"] = "Girdle of the Mentor", ["classPriority"] = "Warrior (Tank)* > Warrior (DPS)* > Warrior", ["note"] = "*No Onslaught"},
    {["itemid"] = "23017", ["itemname"] = "Veil of Eclipse", ["classPriority"] = "Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23014", ["itemname"] = "Iblis, Blade of the Fallen Seraph", ["classPriority"] = "Rogue (Swords) = Warrior (DPS)*", ["note"] = "*Edgemaster Prio"},
    -- Gothik the Harvester
    {["itemid"] = "23073", ["itemname"] = "Boots of Displacement", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23032", ["itemname"] = "Glacial Headdress", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23020", ["itemname"] = "Polar Helmet", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23023", ["itemname"] = "Sadist's Collar", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23021", ["itemname"] = "The Soul Harvester's Bindings", ["classPriority"] = "Mage", ["note"] = ""},
    -- The Four Horsemen
    {["itemid"] = "22691", ["itemname"] = "Corrupted Ashbringer", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23071", ["itemname"] = "Leggings of Apocalypse", ["classPriority"] = "Druid (Feral) = Shaman (Enhance)", ["note"] = ""},
    {["itemid"] = "22809", ["itemname"] = "Maul of the Redeemed Crusader", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23025", ["itemname"] = "Seal of the Damned", ["classPriority"] = "Warlock > Mage", ["note"] = ""},
    {["itemid"] = "22811", ["itemname"] = "Soulstring", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23027", ["itemname"] = "Warmth of Forgiveness", ["classPriority"] = "None", ["note"] = ""},

-- Plague Wing --
    -- Noth the Plaguebringer
    {["itemid"] = "23030", ["itemname"] = "Cloak of the Scourge", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23029", ["itemname"] = "Noth's Frigid Heart", ["classPriority"] = "Healers*", ["note"] = "*Prio Lockout with Sapphiron's Right Eye"},
    {["itemid"] = "23031", ["itemname"] = "Band of the Inevitable", ["classPriority"] = "Warlock > Mage = Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23028", ["itemname"] = "Hailstone Band", ["classPriority"] = "Melee", ["note"] = ""},
    {["itemid"] = "22816", ["itemname"] = "Hatchet of Sundered Bone", ["classPriority"] = "Warrior (DPS)* > Warrior (DPS)", ["note"] = "*Orc / Edgemaster Prio"},
    {["itemid"] = "23006", ["itemname"] = "Libram of Light", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23005", ["itemname"] = "Totem of Flowing Water", ["classPriority"] = "Shaman (Resto)", ["note"] = ""},
    -- Heigan the Unclean
    {["itemid"] = "23068", ["itemname"] = "Legplates of Carnage", ["classPriority"] = "Warrior (DPS)", ["note"] = ""},
    {["itemid"] = "23033", ["itemname"] = "Icy Scale Coif", ["classPriority"] = "Hunter = Shaman (Enhance)", ["note"] = ""},
    {["itemid"] = "23035", ["itemname"] = "Preceptor's Hat", ["classPriority"] = "Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23019", ["itemname"] = "Icebane Helmet", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23036", ["itemname"] = "Necklace of Necropsy", ["classPriority"] = "Healers", ["note"] = ""},
    -- Loatheb
    {["itemid"] = "23038", ["itemname"] = "Band of Unnatural Forces", ["classPriority"] = "Melee", ["note"] = ""},
    {["itemid"] = "23039", ["itemname"] = "The Eye of Nerub", ["classPriority"] = "Hunter", ["note"] = ""},
    {["itemid"] = "23037", ["itemname"] = "Ring of Spiritual Fervor", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22800", ["itemname"] = "Brimstone Staff", ["classPriority"] = "Warlock* = Mage*", ["note"] = "*Prio Lockout with Wraith + Left Eye"},
    {["itemid"] = "23042", ["itemname"] = "Loatheb's Reflection", ["classPriority"] = "None", ["note"] = ""},
    
-- Spider Wing --
    -- Anub'Rekhan
    {["itemid"] = "22938", ["itemname"] = "Cryptfiend Silk Cloak", ["classPriority"] = "Tanks", ["note"] = ""},
    {["itemid"] = "22939", ["itemname"] = "Band of Unanswered Prayers", ["classPriority"] = "Healers", ["note"] = ""},
    {["itemid"] = "22937", ["itemname"] = "Gem of Nerubis", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22935", ["itemname"] = "Touch of Frost", ["classPriority"] = "Healers > Melee > Casters", ["note"] = ""},
    {["itemid"] = "22936", ["itemname"] = "Wristguards of Vengeance", ["classPriority"] = "Warrior (DPS) > Warrior (Tank)", ["note"] = ""},
    -- Grand Widow Faerlina
    {["itemid"] = "22940", ["itemname"] = "Icebane Pauldrons", ["classPriority"] = "Warrior (DPS)", ["note"] = ""},
    {["itemid"] = "22943", ["itemname"] = "Malice Stone Pendant", ["classPriority"] = "Mage = Warlock", ["note"] = ""},
    {["itemid"] = "22941", ["itemname"] = "Polar Shoulder Pads", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22942", ["itemname"] = "The Widow's Embrace", ["classPriority"] = "Healers", ["note"] = ""},
    {["itemid"] = "22806", ["itemname"] = "Widow's Remorse", ["classPriority"] = "Warrior (Tank)* > Rogue (Swords)", ["note"] = "*Edgemaster Prio"},
    -- Maexxna
    {["itemid"] = "23220", ["itemname"] = "Crystal Webbed Robe", ["classPriority"] = "Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "22954", ["itemname"] = "Kiss of the Spider", ["classPriority"] = "Druid (Bear) = Warrior (DPS) = Rogue", ["note"] = "*Prio Lockout with Crest / Jom Gabbar Trinket"},
    {["itemid"] = "22804", ["itemname"] = "Maexxna's Fang", ["classPriority"] = "Rogue (Dagger) > Warrior (DPS)* > Melee", ["note"] = "*Warrior (DPS) has AGCL / Edge"},
    {["itemid"] = "22947", ["itemname"] = "Pendant of Forgotten Names", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "22807", ["itemname"] = "Wraith Blade", ["classPriority"] = "Warlock* = Mage*", ["note"] = "*Prio Lockout with Brimstone Staff"},

-- Frostwyrm Lair --
    -- Sapphiron
    {["itemid"] = "23242", ["itemname"] = "Claw of the Frost Wyrm", ["classPriority"] = "Rogue = Warrior (DPS) > Hunter", ["note"] = ""},
    {["itemid"] = "23050", ["itemname"] = "Cloak of the Necropolis", ["classPriority"] = "Mage = Warlock > Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23047", ["itemname"] = "Eye of the Dead", ["classPriority"] = "Healers", ["note"] = ""},
    {["itemid"] = "23040", ["itemname"] = "Glyph of Deflection", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23049", ["itemname"] = "Sapphiron's Left Eye", ["classPriority"] = "Warlock* = Mage*", ["note"] = "*Prio Lockout with Brimstone Staff"},
    {["itemid"] = "23048", ["itemname"] = "Sapphiron's Right Eye", ["classPriority"] = "Healers*", ["note"] = "*Prio Lockout with Noth's Frigid Heart"},
    {["itemid"] = "23045", ["itemname"] = "Shroud of Dominion", ["classPriority"] = "Hunter = Melee", ["note"] = ""},
    {["itemid"] = "23041", ["itemname"] = "Slayer's Crest", ["classPriority"] = "Melee* = Hunter", ["note"] = "*Prio Lockout with KotS / Jom Gabbar Trinkets"},
    {["itemid"] = "23043", ["itemname"] = "The Face of Death", ["classPriority"] = "Warrior (Tank)", ["note"] = ""},
    {["itemid"] = "23046", ["itemname"] = "The Restrained Essence of Sapphiron", ["classPriority"] = "Warlock > Mage > Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23545", ["itemname"] = "Power of the Scourge", ["classPriority"] = "Casters", ["note"] = ""},
    {["itemid"] = "23547", ["itemname"] = "Resilience of the Scourge", ["classPriority"] = "Healers", ["note"] = ""},
    {["itemid"] = "23548", ["itemname"] = "Might of the Scourge", ["classPriority"] = "Physical DPS = Tanks", ["note"] = ""},
    {["itemid"] = "23549", ["itemname"] = "Fortitude of the Scourge", ["classPriority"] = "Tanks > Warlock", ["note"] = ""},
    -- Kel'Thuzad
    {["itemid"] = "22821", ["itemname"] = "Doomfinger", ["classPriority"] = "Mage > Warlock", ["note"] = ""},
    {["itemid"] = "23057", ["itemname"] = "Gem of Trapped Innocents", ["classPriority"] = "Mage = Warlock", ["note"] = ""},
    {["itemid"] = "23054", ["itemname"] = "Gressil, Dawn of Ruin", ["classPriority"] = "Warrior (DPS)* = Rogue (Sword) > Warrior (Tank)", ["note"] = "*Edgemaster Prio"},
    {["itemid"] = "23056", ["itemname"] = "Hammer of the Twisting Nether", ["classPriority"] = "Healer", ["note"] = ""},
    {["itemid"] = "22802", ["itemname"] = "Kingsfall", ["classPriority"] = "Rogue (Dagger) > Warrior* > Hunter", ["note"] = "*Warrior (DPS) with AGCL / Edge has prio"},
    {["itemid"] = "22812", ["itemname"] = "Nerubian Slavemaker", ["classPriority"] = "Hunter > Warrior = Rogue", ["note"] = ""},
    {["itemid"] = "22798", ["itemname"] = "Might of Menethil", ["classPriority"] = "Shaman (Enhance) > Warrior", ["note"] = ""},
    {["itemid"] = "22819", ["itemname"] = "Shield of Condemnation", ["classPriority"] = "Shaman (Resto)", ["note"] = ""},
    {["itemid"] = "22799", ["itemname"] = "Soulseeker", ["classPriority"] = "Mage > Warlock = Priest (Shadow)", ["note"] = ""},
    {["itemid"] = "23053", ["itemname"] = "Stormrage's Talisman of Seething", ["classPriority"] = "Melee = Hunter", ["note"] = ""},
    {["itemid"] = "22520", ["itemname"] = "The Phylactery of Kel'Thuzad", ["classPriority"] = "Tanks* > DPS", ["note"] = "*Tank without DFT Prio"},
    {["itemid"] = "23577", ["itemname"] = "The Hungering Cold", ["classPriority"] = "Warrior (Tank)> Rogue (Sword)* > Warrior (DPS)*", ["note"] = "*If Warrior (DPS) has CTS or better MH then "=" Prio"},
    -- Rings
    {["itemid"] = "23064", ["itemname"] = "Ring of the Dreamwalker", ["classPriority"] = "Druid", ["note"] = ""},
    {["itemid"] = "23067", ["itemname"] = "Ring of the Cryptstalker", ["classPriority"] = "Hunter", ["note"] = ""},
    {["itemid"] = "23062", ["itemname"] = "Frostfire Ring", ["classPriority"] = "Mage", ["note"] = ""},
    {["itemid"] = "23066", ["itemname"] = "Ring of Repemption ", ["classPriority"] = "Paladin", ["note"] = ""},
    {["itemid"] = "23061", ["itemname"] = "Ring of Faith", ["classPriority"] = "Priest", ["note"] = ""},
    {["itemid"] = "23060", ["itemname"] = "Bonescythe Ring", ["classPriority"] = "Rogue", ["note"] = ""},
    {["itemid"] = "23065", ["itemname"] = "Ring of the Earthshatterer", ["classPriority"] = "Shaman", ["note"] = ""},
    {["itemid"] = "23063", ["itemname"] = "Plagueheart Ring", ["classPriority"] = "Warlock", ["note"] = ""},
    {["itemid"] = "23059", ["itemname"] = "Ring of the Dreadnaught", ["classPriority"] = "Warrior", ["note"] = ""},
    -- Atiesh
    {["itemid"] = "22726", ["itemname"] = "Splinter of Atiesh", ["classPriority"] = "Zynnea = Kelthiz = Alopias", ["note"] = "/Roll on Drop on first drop"},  
    {["itemid"] = "22733", ["itemname"] = "Staff Head of Atiesh", ["classPriority"] = "Zynnea = Kelthiz = Alopias", ["note"] = "/Roll on Drop on first drop"},
    {["itemid"] = "22734", ["itemname"] = "Base of Atiesh", ["classPriority"] = "Zynnea = Kelthiz = Alopias", ["note"] = "/Roll on Drop on first drop"},

-- Trash Drops & Tier Tokens
    -- Trash
    {["itemid"] = "23666", ["itemname"] = "Belt of the Grand Crusader", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23226", ["itemname"] = "Ghoul Skin Tunic", ["classPriority"] = "Druid (Feral) > Melee", ["note"] = ""},
    {["itemid"] = "23663", ["itemname"] = "Girdle of Elemental Fury", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23044", ["itemname"] = "Harbinger of Doom", ["classPriority"] = "Rogue (Dagger) > Warrior (DPS)* > Melee", ["note"] = "*Warrior has AGCL / Edge"},
    {["itemid"] = "23668", ["itemname"] = "Leggings of the Grand Crusader", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23221", ["itemname"] = "Misplaced Servo Arm", ["classPriority"] = "Melee = Shaman (Enhance)*", ["note"] = "*Shamans will use for TBC"},
    {["itemid"] = "23069", ["itemname"] = "Necro-Knight's Garb", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23667", ["itemname"] = "Spaulders of the Grand Crusader", ["classPriority"] = "None", ["note"] = ""},
    {["itemid"] = "23237", ["itemname"] = "Ring of the Eternal Flame", ["classPriority"] = "Mage > Warlock", ["note"] = ""},
    {["itemid"] = "23238", ["itemname"] = "Stygian Buckler", ["classPriority"] = "None", ["note"] = ""},
    -- Mage / Warlock / Priest
    {["itemid"] = "22367", ["itemname"] = "Desecrated Circlet", ["classPriority"] = "Mage = Warlock = Priest (Holy)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22368", ["itemname"] = "Desecrated Shoulderpads", ["classPriority"] = "Warlock = Priest (Holy) > Mage", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22351", ["itemname"] = "Desecrated Robe", ["classPriority"] = "Mage = Warlock > Priest (Holy)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22369", ["itemname"] = "Desecrated Bindings", ["classPriority"] = "Priest (Holy) > Mage = Warlock", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22371", ["itemname"] = "Desecrated Gloves", ["classPriority"] = "Priest (Holy) > Mage = Warlock", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22370", ["itemname"] = "Desecrated Belt", ["classPriority"] = "Priest (Holy) = Warlock > Mage", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22366", ["itemname"] = "Desecrated Leggings", ["classPriority"] = "Warlock > Priest (Holy) = Mage", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22372", ["itemname"] = "Desecrated Sandals", ["classPriority"] = "Mage = Warlock = Priest (Holy)", ["note"] = "Prio will remain until guild decides to remove"},
    -- Shaman / Druid / Hunter / Paladin
    {["itemid"] = "22360", ["itemname"] = "Desecrated Headpiece", ["classPriority"] = "Shaman (Resto) = Hunter > Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22361", ["itemname"] = "Desecrated Spaulders", ["classPriority"] = "Shaman (Resto) = Hunter = Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22350", ["itemname"] = "Desecrated Tunic", ["classPriority"] = "Shaman (Resto) = Hunter = Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22362", ["itemname"] = "Desecrated Wristguards", ["classPriority"] = "Shaman (Resto) = Hunter > Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22364", ["itemname"] = "Desecrated Handguards", ["classPriority"] = "Shaman (Resto) = Druid (Resto) > Hunter", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22363", ["itemname"] = "Desecrated Girdle", ["classPriority"] = "Shaman (Resto) = Hunter = Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22359", ["itemname"] = "Desecrated Legguards", ["classPriority"] = "Shaman (Resto) = Hunter = Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22365", ["itemname"] = "Desecrated Boots", ["classPriority"] = "Shaman (Resto) = Hunter = Druid (Resto)", ["note"] = "Prio will remain until guild decides to remove"},
    -- Warrior / Rogue
    {["itemid"] = "22353", ["itemname"] = "Desecrated Helmet", ["classPriority"] = "Warrior (Tank) > Rogue > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22349", ["itemname"] = "Desecrated Breastplate", ["classPriority"] = "Rogue = Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22354", ["itemname"] = "Desecrated Pauldrons", ["classPriority"] = "Rogue > Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22355", ["itemname"] = "Desecrated Bracers", ["classPriority"] = "Warrior (Tank) > Rogue > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22357", ["itemname"] = "Desecrated Gauntlets", ["classPriority"] = "Rogue > Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22356", ["itemname"] = "Desecrated Waistguard", ["classPriority"] = "Rogue > Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22352", ["itemname"] = "Desecrated Legplates", ["classPriority"] = "Rogue > Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
    {["itemid"] = "22358", ["itemname"] = "Desecrated Sabatons", ["classPriority"] = "Rogue > Warrior (Tank) > Warrior (DPS)", ["note"] = "Prio will remain until guild decides to remove"},
}